const propNum = [
  {
    numero: 0,
    color: "verde",
    paridad: "par",
    mayme: null,
    docena: null,
    columna: null,
  },
  {
    numero: 1,
    color: "rojo",
    paridad: "impar",
    mayme: "menor",
    docena: "1",
    columna: "1",
  },
  {
    numero: 2,
    color: "negro",
    paridad: "par",
    mayme: "menor",
    docena: "1",
    columna: "2",
  },
  {
    numero: 3,
    color: "rojo",
    paridad: "impar",
    mayme: "menor",
    docena: "1",
    columna: "3",
  },
  {
    numero: 4,
    color: "negro",
    paridad: "par",
    mayme: "menor",
    docena: "1",
    columna: "1",
  },
  {
    numero: 5,
    color: "rojo",
    paridad: "impar",
    mayme: "menor",
    docena: "1",
    columna: "2",
  },
  {
    numero: 6,
    color: "negro",
    paridad: "par",
    mayme: "menor",
    docena: "1",
    columna: "3",
  },
  {
    numero: 7,
    color: "rojo",
    paridad: "impar",
    mayme: "menor",
    docena: "1",
    columna: "1",
  },
  {
    numero: 8,
    color: "negro",
    paridad: "par",
    mayme: "menor",
    docena: "1",
    columna: "2",
  },
  {
    numero: 9,
    color: "rojo",
    paridad: "impar",
    mayme: "menor",
    docena: "1",
    columna: "3",
  },
  {
    numero: 10,
    color: "negro",
    paridad: "par",
    mayme: "menor",
    docena: "1",
    columna: "1",
  },
  {
    numero: 11,
    color: "negro",
    paridad: "impar",
    mayme: "menor",
    docena: "1",
    columna: "2",
  },
  {
    numero: 12,
    color: "rojo",
    paridad: "par",
    mayme: "menor",
    docena: "1",
    columna: "3",
  },
  {
    numero: 13,
    color: "negro",
    paridad: "impar",
    mayme: "menor",
    docena: "2",
    columna: "1",
  },
  {
    numero: 14,
    color: "rojo",
    paridad: "par",
    mayme: "menor",
    docena: "2",
    columna: "2",
  },
  {
    numero: 15,
    color: "negro",
    paridad: "impar",
    mayme: "menor",
    docena: "2",
    columna: "3",
  },
  {
    numero: 16,
    color: "rojo",
    paridad: "par",
    mayme: "menor",
    docena: "2",
    columna: "1",
  },
  {
    numero: 17,
    color: "negro",
    paridad: "impar",
    mayme: "menor",
    docena: "2",
    columna: "2",
  },
  {
    numero: 18,
    color: "rojo",
    paridad: "par",
    mayme: "menor",
    docena: "2",
    columna: "3",
  },
  {
    numero: 19,
    color: "rojo",
    paridad: "impar",
    mayme: "mayor",
    docena: "2",
    columna: "1",
  },
  {
    numero: 20,
    color: "negro",
    paridad: "par",
    mayme: "mayor",
    docena: "2",
    columna: "2",
  },
  {
    numero: 21,
    color: "rojo",
    paridad: "impar",
    mayme: "mayor",
    docena: "2",
    columna: "3",
  },
  {
    numero: 22,
    color: "negro",
    paridad: "par",
    mayme: "mayor",
    docena: "2",
    columna: "1",
  },
  {
    numero: 23,
    color: "rojo",
    paridad: "impar",
    mayme: "mayor",
    docena: "2",
    columna: "2",
  },
  {
    numero: 24,
    color: "negro",
    paridad: "par",
    mayme: "mayor",
    docena: "2",
    columna: "3",
  },
  {
    numero: 25,
    color: "rojo",
    paridad: "impar",
    mayme: "mayor",
    docena: "3",
    columna: "1",
  },
  {
    numero: 26,
    color: "negro",
    paridad: "par",
    mayme: "mayor",
    docena: "3",
    columna: "2",
  },
  {
    numero: 27,
    color: "rojo",
    paridad: "impar",
    mayme: "mayor",
    docena: "3",
    columna: "3",
  },
  {
    numero: 28,
    color: "negro",
    paridad: "par",
    mayme: "mayor",
    docena: "3",
    columna: "1",
  },
  {
    numero: 29,
    color: "negro",
    paridad: "impar",
    mayme: "mayor",
    docena: "3",
    columna: "2",
  },
  {
    numero: 30,
    color: "rojo",
    paridad: "par",
    mayme: "mayor",
    docena: "3",
    columna: "3",
  },
  {
    numero: 31,
    color: "negro",
    paridad: "impar",
    mayme: "mayor",
    docena: "3",
    columna: "1",
  },
  {
    numero: 32,
    color: "rojo",
    paridad: "par",
    mayme: "mayor",
    docena: "3",
    columna: "2",
  },
  {
    numero: 33,
    color: "negro",
    paridad: "impar",
    mayme: "mayor",
    docena: "3",
    columna: "3",
  },
  {
    numero: 34,
    color: "rojo",
    paridad: "par",
    mayme: "mayor",
    docena: "3",
    columna: "1",
  },
  {
    numero: 35,
    color: "negro",
    paridad: "impar",
    mayme: "mayor",
    docena: "3",
    columna: "2",
  },
  {
    numero: 36,
    color: "rojo",
    paridad: "par",
    mayme: "mayor",
    docena: "3",
    columna: "3",
  },
];

module.exports = propNum;
